#!/usr/bin/python
# -*- coding: UTF-8 -*-
from urllib.request import urlopen
from urllib.error import HTTPError
from bs4 import BeautifulSoup


def getTitle(url):
    try:
         html = urlopen(url)
    except HTTPError as e:                #http异常处理
        retrurn "http异常"

    try:
        bsObj = BeautifulSoup(html.read(), 'lxml')
        title = bsObj.title
    except ArithmeticError as e:           #标签异常处理
        return "标签异常"
    return title
filename = "url.txt"
with open(filename)  as  file_object:
    lines = file_object.readlines()
for url in lines:
    title =getTitle(url)
    if title == NOne:
        print("title  没有找到")
    else:
        print(title)
